version: '3.8'
services:
  postgres:
    # build:
    #   context: .
    image: postgres-app
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      DB_NAMES: "inventory,auth"
    ports:
      - 5432:5432
    restart: always

  mongo:
    image: mongo-app
    container_name: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: inventory
